<?php

namespace booksBundle\Repository;

/**
 * LivreOccasionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreOccasionRepository extends \Doctrine\ORM\EntityRepository
{
}
